services:
  trainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.trainer
    container_name: chessrecast-ai-poc
    runtime: nvidia
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../trainer:/workspace/trainer
      - ../trainer/checkpoints:/workspace/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_LAUNCH_BLOCKING=1
